# Generated by Django 5.0 on 2026-02-15 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('note', 'Text Note'), ('url', 'URL')], max_length=10)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Currently Processing'), ('completed', 'Ready for Query'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'db_table': 'rag_inbox_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type'], name='rag_inbox_c_content_e110ca_idx'), models.Index(fields=['status'], name='rag_inbox_c_status_699748_idx'), models.Index(fields=['-created_at'], name='rag_inbox_c_created_42a9f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('processing_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'db_table': 'rag_inbox_querylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='rag_inbox_q_created_4d6667_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('embedding_json', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag_inbox.content')),
            ],
            options={
                'verbose_name': 'Text Chunk',
                'verbose_name_plural': 'Text Chunks',
                'db_table': 'rag_inbox_chunk',
                'ordering': ['content', 'order'],
                'indexes': [models.Index(fields=['content'], name='rag_inbox_c_content_096e78_idx'), models.Index(fields=['order'], name='rag_inbox_c_order_dd8567_idx')],
            },
        ),
    ]
